//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity_Interception.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("app.log")]
        public string LogFileFolder {
            get {
                return ((string)(this["LogFileFolder"]));
            }
            set {
                this["LogFileFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20000")]
        public int MaxLogFileSize {
            get {
                return ((int)(this["MaxLogFileSize"]));
            }
            set {
                this["MaxLogFileSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Information")]
        public string LogToCategoryNamed {
            get {
                return ((string)(this["LogToCategoryNamed"]));
            }
            set {
                this["LogToCategoryNamed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rolling Flat File Trace Listener")]
        public string RollingFile {
            get {
                return ((string)(this["RollingFile"]));
            }
            set {
                this["RollingFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Text Formatter")]
        public string TextFormatterNamed {
            get {
                return ((string)(this["TextFormatterNamed"]));
            }
            set {
                this["TextFormatterNamed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("logging")]
        public string UnityPolicyName {
            get {
                return ((string)(this["UnityPolicyName"]));
            }
            set {
                this["UnityPolicyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Method Çalışıyor...")]
        public string LoggingHandlerBeforeMessage {
            get {
                return ((string)(this["LoggingHandlerBeforeMessage"]));
            }
            set {
                this["LoggingHandlerBeforeMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Method Çalıştı...")]
        public string LoggingHandlerAfterMessage {
            get {
                return ((string)(this["LoggingHandlerAfterMessage"]));
            }
            set {
                this["LoggingHandlerAfterMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1001")]
        public int LoggingHandlerEventId {
            get {
                return ((int)(this["LoggingHandlerEventId"]));
            }
            set {
                this["LoggingHandlerEventId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoggingHandlerLogBeforeCall {
            get {
                return ((bool)(this["LoggingHandlerLogBeforeCall"]));
            }
            set {
                this["LoggingHandlerLogBeforeCall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoggingHandlerLogAfterCall {
            get {
                return ((bool)(this["LoggingHandlerLogAfterCall"]));
            }
            set {
                this["LoggingHandlerLogAfterCall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoggingHandlerIncludeParameters {
            get {
                return ((bool)(this["LoggingHandlerIncludeParameters"]));
            }
            set {
                this["LoggingHandlerIncludeParameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoggingHandlerIncludeCallStack {
            get {
                return ((bool)(this["LoggingHandlerIncludeCallStack"]));
            }
            set {
                this["LoggingHandlerIncludeCallStack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoggingHandlerIncludeCallTime {
            get {
                return ((bool)(this["LoggingHandlerIncludeCallTime"]));
            }
            set {
                this["LoggingHandlerIncludeCallTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LoggingHandlerPriority {
            get {
                return ((int)(this["LoggingHandlerPriority"]));
            }
            set {
                this["LoggingHandlerPriority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LoggingHandlerOrder {
            get {
                return ((int)(this["LoggingHandlerOrder"]));
            }
            set {
                this["LoggingHandlerOrder"] = value;
            }
        }
    }
}
